[package]
name = "clipstack"
version = "0.1.0"
authors = ["Richard McCormack <rmccormack@ebsco.com>"]

[dependencies]
bitflags = "1"
dirs = "1"
log = "0.4"
pretty_env_logger = "0.2"
winapi = { version = "0.3", features = ["commctrl", "winuser", "errhandlingapi", "winbase", "shellapi", "windowsx"] }

[profile.release]
lto = true